services:
  fakenos:
    container_name: fakenos
    hostname: 'fakenos'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      fakenosnet0:
        ipv4_address: 10.100.0.2
    volumes:
      # bind folder with tests to fakenos container
      - type: bind
        source: ./tests/
        target: /tmp/tests/
      # bind FakeNOS packages to Python3.9 for development/debugging
      - type: bind
        source: ./fakenos/
        target: /usr/local/lib/python3.9/site-packages/fakenos/        
        
networks:
  fakenosnet0:
    ipam:
      config:
        - subnet: 10.100.0.0/24
          gateway: 10.100.0.1
