default:
  username: "user"
  password: "user"
  port: [10000, 60000]
  server: 
    plugin: "ParamikoSshServer"
    configuration: 
      address: "0.0.0.0"
      timeout: 1
  shell: {plugin: "CMDShell", configuration: {}}
  nos: {plugin: "cisco_ios", configuration: {}}
  
hosts:
  router: {count: 10, port: [6001, 7000]}
