name: ci 
on:
  push:
    branches:
      - master
      - dev
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: "Install Poetry"
        run: "curl -sSL https://install.python-poetry.org | python -"
        shell: "bash"
      - name: "Add poetry to PATH"
        run: "ln -s /root/.local/bin/poetry /usr/local/bin/poetry"
        shell: "bash"
      - name: "Log: Check cache"
        run: "echo Checking cache"
        shell: "bash"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: "Cache"
        uses: "actions/cache@v4"
        id: "cached-poetry"
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ".cache"
          restore-keys: |
            mkdocs-material-
      - name: "Install environment"
        run: "poetry install"
        shell: "bash"
      - name: "Log: Check poetry"
        run: "echo "
        shell: "bash"
      - run: poetry run mkdocs gh-deploy --force